import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, basename } from 'node:path';
import * as core from '@actions/core';
import * as github from '@actions/github';
import Cloudflare from 'cloudflare';
import { parseWorkersInput } from './config.js';
import { parseWranglerConfig, rewriteWranglerConfig, rewriteKVNamespaces, rewriteWorkflowNames, rewriteVars, rewriteWorkerName, type DatabaseReplacement, type KVReplacement, type WorkflowReplacement } from './wrangler.js';
import { createDatabase } from './d1.js';
import { createKVNamespace } from './kv.js';
import { teardownDatabases, teardownKVNamespaces, teardownWorkers } from './teardown.js';
import { runMigrations, uploadPreviewVersion } from './preview.js';
import { postPreviewComment, postTeardownComment } from './comment.js';
import { cleanupOrphanedDatabases } from './cleanup.js';
import type { PreviewResult, DatabaseResult, KVNamespaceResult } from './types.js';

const PREVIEW_ACTIONS = new Set(['opened', 'synchronize', 'reopened']);

/**
 * Main orchestration function. Reads action inputs, dispatches to the correct
 * lifecycle path based on event type.
 */
export async function run(): Promise<void> {
  try {
    const cloudflareApiToken = core.getInput('cloudflare_api_token');
    const cloudflareAccountId = core.getInput('cloudflare_account_id');
    const workersInput = core.getInput('workers');
    const githubToken = core.getInput('github_token');
    const shouldComment = core.getBooleanInput('comment');
    const cleanup = core.getBooleanInput('cleanup');
    const secretsInput = core.getInput('secrets');
    const secrets: Record<string, string> = secretsInput ? JSON.parse(secretsInput) : {};

    // Mask secret values in CI logs
    for (const value of Object.values(secrets)) {
      core.setSecret(value);
    }

    const client = new Cloudflare({ apiToken: cloudflareApiToken });
    const repo = github.context.repo;
    const action = github.context.payload.action ?? '';

    // Cleanup mode — independent of PR lifecycle
    if (cleanup) {
      await cleanupOrphanedDatabases(client, cloudflareAccountId, githubToken, repo);
      return;
    }

    const prNumber = github.context.payload.pull_request?.number;
    if (!prNumber) {
      throw new Error('No pull request number found in event payload');
    }

    const cfEnv = { apiToken: cloudflareApiToken, accountId: cloudflareAccountId };

    // Closed PR — teardown only
    if (action === 'closed') {
      const workers = parseWorkersInput(workersInput);
      await teardownDatabases(client, cloudflareAccountId, prNumber);
      await teardownKVNamespaces(client, cloudflareAccountId, prNumber);
      await teardownWorkers(workers, prNumber, cfEnv);
      if (shouldComment) {
        await postTeardownComment(githubToken, repo, prNumber);
      }
      return;
    }

    // Preview lifecycle (opened / synchronize / reopened)
    if (!PREVIEW_ACTIONS.has(action)) {
      core.info(`Ignoring unsupported action: ${action}`);
      return;
    }

    const workers = parseWorkersInput(workersInput);

    // Step 1: Teardown existing preview resources
    await teardownDatabases(client, cloudflareAccountId, prNumber);
    await teardownKVNamespaces(client, cloudflareAccountId, prNumber);

    // Step 2: Provision databases and KV namespaces (deduplicated)
    const dbMap = new Map<string, { previewName: string; previewId: string }>();
    const kvMap = new Map<string, { previewTitle: string; previewId: string; bindingName: string }>();
    const allPreviews: PreviewResult[] = [];
    const allDatabaseResults: DatabaseResult[] = [];
    const allKVResults: KVNamespaceResult[] = [];

    // Parse all worker configs
    // When deployConfig is set, read the deploy-ready config (e.g. generated by @cloudflare/vite-plugin)
    const workerConfigs = workers.map((worker) => {
      const configPath = worker.deployConfig ?? worker.path;
      const content = readFileSync(configPath, 'utf-8');
      const config = parseWranglerConfig(content);
      return { worker, config, originalContent: content, configPath };
    });

    // Create preview databases, deduplicating by original database_name
    for (const { config } of workerConfigs) {
      for (const binding of config.d1_databases) {
        if (dbMap.has(binding.database_name)) continue;

        const previewName = `preview-pr-${prNumber}-${binding.database_name}`;
        const previewId = await createDatabase(client, cloudflareAccountId, previewName);
        dbMap.set(binding.database_name, { previewName, previewId });
      }
    }

    // Create preview KV namespaces, deduplicating by original id
    for (const { config } of workerConfigs) {
      for (const binding of config.kv_namespaces) {
        if (kvMap.has(binding.id)) continue;

        const previewTitle = `preview-pr-${prNumber}-${binding.binding}`;
        const previewId = await createKVNamespace(client, cloudflareAccountId, previewTitle);
        kvMap.set(binding.id, { previewTitle, previewId, bindingName: binding.binding });
      }
    }

    // Build workflow name replacements (deduplicated by original name)
    const workflowMap = new Map<string, WorkflowReplacement>();
    for (const { config } of workerConfigs) {
      for (const wf of config.workflows) {
        if (workflowMap.has(wf.name)) continue;
        workflowMap.set(wf.name, { previewName: `preview-pr-${prNumber}-${wf.name}` });
      }
    }

    // Step 3: Rewrite configs, run migrations (deduplicated), and upload each worker
    const migratedDbs = new Set<string>();
    const tempDir = mkdtempSync(join(tmpdir(), 'cf-preview-'));

    for (const [workerIndex, { worker, config, originalContent, configPath }] of workerConfigs.entries()) {
      // Build D1 replacements map for this worker's bindings
      const dbReplacements = new Map<string, DatabaseReplacement>();
      for (const binding of config.d1_databases) {
        const entry = dbMap.get(binding.database_name);
        if (entry) {
          dbReplacements.set(binding.database_name, entry);
        }
      }

      // Build KV replacements map for this worker's bindings
      const kvReplacements = new Map<string, KVReplacement>();
      for (const binding of config.kv_namespaces) {
        const entry = kvMap.get(binding.id);
        if (entry) {
          kvReplacements.set(binding.id, { previewId: entry.previewId });
        }
      }

      // Build workflow replacements map for this worker's bindings
      const wfReplacements = new Map<string, WorkflowReplacement>();
      for (const wf of config.workflows) {
        const entry = workflowMap.get(wf.name);
        if (entry) {
          wfReplacements.set(wf.name, entry);
        }
      }

      // Rewrite config (D1 first, then KV, then workflows)
      let rewritten = originalContent;
      if (dbReplacements.size > 0) {
        rewritten = rewriteWranglerConfig(rewritten, dbReplacements);
      }
      if (kvReplacements.size > 0) {
        rewritten = rewriteKVNamespaces(rewritten, kvReplacements);
      }
      if (wfReplacements.size > 0) {
        rewritten = rewriteWorkflowNames(rewritten, wfReplacements);
      }
      if (Object.keys(secrets).length > 0) {
        rewritten = rewriteVars(rewritten, secrets);
      }
      // Always rename the worker to an isolated PR worker so the production
      // worker is never touched by the preview action.
      const prWorkerName = `${config.name}-pr-${prNumber}`;
      rewritten = rewriteWorkerName(rewritten, prWorkerName);

      // Write the rewritten config to a temp file so the original is never mutated.
      const tempConfigPath = join(tempDir, `${workerIndex}-${basename(configPath)}`);
      writeFileSync(tempConfigPath, rewritten, 'utf-8');

      // Build updated bindings, filtering out already-migrated databases
      const updatedBindings = config.d1_databases
        .filter((b) => !migratedDbs.has(b.database_name))
        .map((b) => {
          const entry = dbMap.get(b.database_name);
          if (entry) {
            return { ...b, database_name: entry.previewName, database_id: entry.previewId };
          }
          return b;
        });

      // Run migrations only for databases not yet migrated
      const migrationsApplied = await runMigrations(updatedBindings, worker.workingDirectory, cfEnv, tempConfigPath);

      // Mark these databases as migrated
      for (const binding of config.d1_databases) {
        migratedDbs.add(binding.database_name);
      }

      // Upload preview version
      const preview = await uploadPreviewVersion(
        config.name,
        worker.workingDirectory,
        prNumber,
        cfEnv,
        tempConfigPath,
      );
      allPreviews.push(preview);

      // Collect database results for this worker (deduplicated)
      for (const binding of config.d1_databases) {
        const entry = dbMap.get(binding.database_name);
        if (entry && !allDatabaseResults.some((r) => r.originalName === binding.database_name)) {
          allDatabaseResults.push({
            originalName: binding.database_name,
            previewName: entry.previewName,
            previewId: entry.previewId,
            migrationsApplied,
          });
        }
      }

      // Collect KV results for this worker (deduplicated)
      for (const binding of config.kv_namespaces) {
        const entry = kvMap.get(binding.id);
        if (entry && !allKVResults.some((r) => r.originalId === binding.id)) {
          allKVResults.push({
            bindingName: entry.bindingName,
            originalId: binding.id,
            previewTitle: entry.previewTitle,
            previewId: entry.previewId,
          });
        }
      }
    }

    // Clean up temp config files
    rmSync(tempDir, { recursive: true, force: true });

    // Step 4: Comment on PR
    if (shouldComment) {
      await postPreviewComment(githubToken, repo, prNumber, allPreviews, allDatabaseResults, allKVResults);
    }

    // Step 5: Set outputs
    const previewUrls: Record<string, string> = {};
    for (const p of allPreviews) {
      previewUrls[p.workerName] = p.previewUrl;
    }

    const databaseIds: Record<string, string> = {};
    for (const d of allDatabaseResults) {
      databaseIds[d.originalName] = d.previewId;
    }

    const kvNamespaceIds: Record<string, string> = {};
    for (const kv of allKVResults) {
      kvNamespaceIds[kv.originalId] = kv.previewId;
    }

    core.setOutput('preview_urls', JSON.stringify(previewUrls));
    core.setOutput('database_ids', JSON.stringify(databaseIds));
    core.setOutput('kv_namespace_ids', JSON.stringify(kvNamespaceIds));
    core.setOutput('preview_alias', `pr-${prNumber}`);
  } catch (error) {
    core.setFailed(error instanceof Error ? error.message : String(error));
  }
}

/* c8 ignore next 3 */
if (!process.env.VITEST) {
  run();
}
